### PR TITLE
Implement trivial paste re-use

### PR DESCRIPTION
**Pull request by arrdem**
Use a buffer local variable to save the paste ID after pasting so that future refheap-baset-buffer\* calls on the same buffer will re-use the original paste.

### CODE REVIEW

**Comment by Raynes** [comment]
The problem with this is that people frequently make separate pastes of the different pieces of code in the same buffer.

**Comment by arrdem** [comment]
I could imagine doing monkey buisness to implement a "paste ID by line range", but then as a user types the linemap will diverge from reality until refheap.el grows a VCS of its own to accomidate. Either no re-use (current state) or something dead naive like this is probably the best solution.

**Comment by Raynes** [comment]
What did we decide to do with this? Looking at it now, it seems like the best solution would be to add a refheap-edit-previous or something so that you can trivially chose to edit or not.

Thoughts?

**Comment by arrdem** [comment]
I agree that refheap-edit-previous is probably the best way to go... or refheap-update-previous as edit-previous implies (in my mind) that it pulls down the text into a buffer and then lets you push the buffer back.

**Comment by Raynes** [comment]
Closing because arrdem is lazy.

**Pull request closed without merging**
