### PR TITLE
Fix emacs lisp mode's language string

### PR DESCRIPTION
**Pull request by ghost**
Change from "Scheme" to "Emacs Lisp"

### CODE REVIEW

**Comment by ghost** [comment]
Just ran into this when testing the package out

**Comment by Raynes** [comment]
This is on purpose. As far as I could (and can) tell, Pygments doesn't have a special Emacs Lisp lexer and suggests you use the scheme lexer (or, I suppose the common lisp lexer would also work). Hence the mapping.

**Comment by Raynes** [comment]
Furthermore, if they do actually have an emacs lisp specific lexer now, this pull request isn't enough to get it -- would also need to update the bootstrap script to pull a newer version of pygments and also make sure it doesn't break everything to shit.

**Comment by ghost** [comment]
Well, refheap itself certainly seems to have "Emacs Lisp" in the language dropdown, so I would think that it should already be dealing with any issues arising from that or it wouldn't be in the dropdown?

**Comment by Raynes** [comment]
The dropdown is the languages that I have specified in this map, and they map to what that map maps them to. Emacs Lisp in the dropdown is mapped to the Scheme lexer. In most cases, it isn't going to matter -- lisps tend to be similar by nature.

EDIT:

On the other hand, are you saying something here is broken? Does the Emacs Lisp selection not do anything at all, or...? What's the actual issue.

**Comment by ghost** [comment]
Right, and so I make a paste with an emacs lisp file and it shows in my pastes as scheme despite there being an option for Emacs Lisp. I don't care what lexer is used, the reason it bothered me is because the site shows the language as Scheme when it has the capablity of showing it as Emacs Lisp.

From the refheap docs, the "language" API field can be anything in the dropdown, not just anything that has a direct lexer.

It is a pretty minor issue, but also a pretty minor fix.

**Comment by Raynes** [comment]
Oh!!! I completely misunderstood the issue. You're totally right. Apologies, sir!

**Comment by ghost** [comment]
Alright, thought we had a communication issue. That's why I spelled it out this time!

**Pull request merged**
